// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdzTqFWw6wSHd_v84ePkNl2BTVQcjebI',
    appId: '1:791653531041:web:aabee4aa7b9047c6d7dfe0',
    messagingSenderId: '791653531041',
    projectId: 'varta-app-5f6ac',
    authDomain: 'varta-app-5f6ac.firebaseapp.com',
    storageBucket: 'varta-app-5f6ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwjvAZTEuEEhYFqDl4Kum-KaH7qWlMzo',
    appId: '1:791653531041:android:d7a343671e918e2dd7dfe0',
    messagingSenderId: '791653531041',
    projectId: 'varta-app-5f6ac',
    storageBucket: 'varta-app-5f6ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOG8MiDoJpptmKqtB4ML9sE2tAV1hORRY',
    appId: '1:791653531041:ios:05ed260a8e886ae1d7dfe0',
    messagingSenderId: '791653531041',
    projectId: 'varta-app-5f6ac',
    storageBucket: 'varta-app-5f6ac.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}