# Generated by Django 5.0.7 on 2024-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
