# Generated by Django 5.0.7 on 2024-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
