# Generated by Django 5.0.7 on 2024-10-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_academicyear_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
    ]
