# Generated by Django 5.0.7 on 2024-08-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherclass',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherdepartment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('classroom', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom')),
            ],
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('class_teacher_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='accounts.classroom')),
                ('departments', models.ManyToManyField(to='accounts.department')),
                ('subject_teacher_of', models.ManyToManyField(related_name='subject_teacher_of', to='accounts.classroom')),
            ],
            bases=('accounts.user',),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
        migrations.DeleteModel(
            name='TeacherDepartment',
        ),
    ]
