# Generated by Django 5.0.7 on 2024-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='lang/english', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
