# Generated by Django 5.0.7 on 2024-10-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_department_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['standard', 'division']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name']},
        ),
        migrations.AlterModelOptions(
            name='studentdetail',
            options={'verbose_name': 'Student Detail', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterModelOptions(
            name='teacherdetail',
            options={'verbose_name': 'Teacher Detail', 'verbose_name_plural': 'Teacher Details'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'verbose_name': 'User Contact', 'verbose_name_plural': 'User Contacts'},
        ),
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-last_used_at'], 'verbose_name': 'User Device', 'verbose_name_plural': 'User Devices'},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('standard', 'division')},
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together={('user', 'contact_type', 'contact_data')},
        ),
    ]
