# Generated by Django 5.0.7 on 2024-10-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_classroom_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='teacherdetail',
            name='class_teacher_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='accounts.classroom'),
        ),
        migrations.AlterField(
            model_name='teacherdetail',
            name='departments',
            field=models.ManyToManyField(related_name='departments', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['standard'], name='accounts_cl_standar_afb1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['standard', 'division'], name='accounts_cl_standar_58f6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['contact_importance', 'contact_type', 'contact_data'], name='accounts_us_contact_583ef6_idx'),
        ),
    ]
