# Generated by Django 5.0.7 on 2024-08-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_id_alter_user_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_of',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_teacher_of',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='accounts.classroom')),
                ('departments', models.ManyToManyField(to='accounts.department')),
                ('subject_teacher_of', models.ManyToManyField(related_name='subject_teacher_of', to='accounts.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_details', to='accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
