# Generated by Django 5.0.7 on 2024-10-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_studentdetail_classroom'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercontact',
            name='accounts_us_contact_583ef6_idx',
        ),
        migrations.RemoveField(
            model_name='usercontact',
            name='contact_importance',
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['contact_type', 'contact_data'], name='accounts_us_contact_8e4912_idx'),
        ),
    ]
