name: app
description: A one-way multi-channel school communications app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dropdown_button2: ^2.3.9
  flutter_otp_text_field: ^1.1.0+2
  mask_text_input_formatter: ^2.9.0
  http: ^1.2.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  dart_jsonwebtoken: ^2.14.0
  flutter_svg: ^2.0.10+1
  skeletonizer: ^1.4.2
  collection: ^1.18.0
  uuid: ^4.5.0
  async: any
  screenshot: ^3.0.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  share_plus: ^10.1.0
  path_provider: ^2.1.4
  file_picker: ^8.1.3
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_native_splash:
  color: "#191919"
  image: assets/images/varta-logo-medium.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/varta-logo-medium.png"
  ios: true

flutter:
  assets:
    - assets/images/abstract-1.svg
    - assets/images/crashed-error.svg
    - assets/images/falling.svg
    - assets/images/relax.svg

    - assets/icons/file-doc.svg
    - assets/icons/file-pdf.svg
    - assets/icons/file-ppt.svg
    - assets/icons/file-xls.svg
    - assets/icons/camera.svg
    - assets/icons/video.svg


  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist/Geist-UltraBlack.ttf
          weight: 900

    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono/GeistMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/GeistMono/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono/GeistMono-Medium.ttf
          weight: 500

  uses-material-design: true
