name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dropdown_button2: ^2.3.9
  flutter_otp_text_field: ^1.1.0+2
  mask_text_input_formatter: ^2.9.0
  http: ^1.2.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  dart_jsonwebtoken: ^2.14.0
  flutter_svg: ^2.0.10+1
  skeletonizer: ^1.4.2
  collection: ^1.18.0
  uuid: ^4.5.0


  async: any
  screenshot: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Black.ttf
          weight: 900
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geist/Geist-UltraBlack.ttf
          weight: 900
        - asset: assets/fonts/Geist/Geist-UltraLight.ttf
          weight: 200

    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono/GeistMono-Black.ttf
          weight: 900
        - asset: assets/fonts/GeistMono/GeistMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/GeistMono/GeistMono-Light.ttf
          weight: 300
        - asset: assets/fonts/GeistMono/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono/GeistMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/GeistMono/GeistMono-UltraBlack.ttf
          weight: 900
        - asset: assets/fonts/GeistMono/GeistMono-UltraLight.ttf
          weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
