# Generated by Django 5.0.7 on 2024-10-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_delete_announcementattachment'),
        ('attachments', '0002_announcementattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='path',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='announcements.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AttachmentHash',
        ),
    ]
