# Generated by Django 5.0.7 on 2024-10-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_rename_name_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.URLField(default='http://example.com', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
