# Generated by Django 5.0.7 on 2024-11-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_delete_announcementattachment'),
        ('attachments', '0005_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement'),
        ),
        migrations.DeleteModel(
            name='AnnouncementAttachment',
        ),
    ]
