# Generated by Django 5.0.7 on 2024-11-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0007_attachment_file_size_in_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
    ]
