# Generated by Django 5.0.7 on 2024-08-27 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.academicyear')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(choices=[('t_class_teacher_of', 'Teacher is the class teacher of standard division'), ('t_subject_teacher_of_standard', 'Teacher is subject teacher of the standard'), ('t_subject_teacher_of_standard_division', 'Teacher is the subject teacher of the standard division'), ('t_department', 'Teacher is of the department'), ('stu_standard', 'Student is of the standard'), ('stu_standard_division', 'Student is of the standard division'), ('stu_all', 'All Students'), ('t_all', 'All Teachers'), ('everyone', 'Everyone in the school')], max_length=48)),
                ('filter_data', models.CharField(max_length=255, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='announcements.announcement')),
            ],
        ),
    ]
