# Generated by Django 5.0.7 on 2024-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementscope',
            name='filter_data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
