# Generated by Django 5.0.7 on 2024-10-08 08:38

import django.db.models.deletion
import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='academic_year',
            field=models.ForeignKey(default=schools.models.AcademicYear.get_current_academic_year, on_delete=django.db.models.deletion.DO_NOTHING, to='schools.academicyear'),
        ),
    ]
