# Generated by Django 5.0.7 on 2024-10-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementAttachment',
        ),
    ]
