# Generated by Django 5.0.7 on 2024-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcementscope_filter_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
